language: java

# safelist
branches:
  only:
  - master
  - stable

before_script:
  - wget https://github.com/epimorphics/elda/archive/elda-2.0.0.tar.gz -O elda.tar.gz
  - tar -xvf elda.tar.gz
  - mv elda-elda-2.0.0 elda
  - cd elda
  - mvn clean package
  - python --version
  - cd ..

jobs:
  include:
    - stage: Create SISSVoc dist
    - script: pwd
    - script: ./build.sh
    - stage: Create SISSVoc dist
    - script: docker-compose build
    - script: docker-compose up -d
    - script: docker-compose ps
    - script: docker-compose logs
