language: java

# safelist
branches:
  only:
  - master
  - stable

install:
  - wget https://github.com/epimorphics/elda/archive/elda-2.0.0.tar.gz -O elda.tar.gz
  - tar -xvf elda.tar.gz
  - mv elda-elda-2.0.0 elda
  - cd elda
  - mvn clean package
  - python --version
  - cd ..
  - ./build.sh
  - docker-compose up -d --build  && docker-compose ps && docker-compose logs && docker-compose down -v

jobs:
  include:
    - script: wget http://localhost:8080/sissvoc/default/concept
