language: java

# safelist
branches:
  only:
  - master
  - stable

before_script:
  - wget https://github.com/epimorphics/elda/archive/elda-2.0.0.tar.gz -O elda.tar.gz
  - tar -xvf elda.tar.gz
  - cd elda-elda-2.0.0
  - mvn clean package
  - python --version

jobs:
  include:
    - stage: Create SISSVoc dist
    - script: echo "Placeholder to create dist"
